name: kazoo-application-ecallmgr
custom_files: null
exposure: private
base_branch: origin/5.3
base_core: kazoo
template: kazoo-application.spec.tmpl
package:
  centos7:
    name: kazoo-application-ecallmgr
    summary: 'Kazoo core application'
    description: |
      KAZOO interface to FreeSWITCH, providing the clustering logic over
      FreeSWITCH to present a single logical switch to the higher levels
      of KAZOO.
    app_name: ecallmgr
    license: 'MPL 2.0'
    group: Productivity/Telephony
    url: 'https://2600hz.org/'
    vendor: 2600Hz
metapackage:
  -
    name: meta-kazoo-applications
    type: required
    branch: '5.3'
    package: kazoo-application-ecallmgr
dependencies: null
