version: 2.1
orbs:
  kazoo: official-2600hz/kazoo@0.3.1
workflows:
  version: 2
  build_branch:
    jobs:
      -
        kazoo/build-preparation:
          context: Private-Builds
          name: 'preparation-<< matrix.platform >>'
          target-type: kapp
          platform: '<< matrix.platform >>'
          matrix:
            parameters:
              platform: [centos-7, rockylinux-8, rockylinux-9]
      -
        kazoo/build:
          context: Private-Builds
          name: 'beams-<< matrix.platform >>'
          platform: '<< matrix.platform >>'
          matrix:
            parameters:
              platform: [centos-7, rockylinux-8, rockylinux-9]
          requires:
            - 'preparation-<< matrix.platform >>'
      -
        kazoo/eunit-tests:
          context: Private-Builds
          requires:
            - preparation-centos-7
      -
        kazoo/code-checks:
          requires:
            - beams-centos-7
      -
        kazoo/docs:
          requires:
            - beams-centos-7
      -
        kazoo/analyze:
          requires:
            - beams-centos-7
      -
        kazoo/integration-test:
          requires:
            - beams-centos-7
      -
        kazoo/build-centos7:
          context: Private-Builds
          target-type: kapp
          requires:
            - beams-centos-7
      -
        kazoo/build-rockylinux8:
          context: Private-Builds
          target-type: kapp
          requires:
            - beams-rockylinux-8
      -
        kazoo/build-rockylinux9:
          context: Private-Builds
          target-type: kapp
          requires:
            - beams-rockylinux-9
  build_release:
    jobs:
      -
        kazoo/build-preparation:
          context: Private-Builds
          name: 'preparation-<< matrix.platform >>'
          target-type: kapp
          platform: '<< matrix.platform >>'
          matrix:
            parameters:
              platform: [centos-7, rockylinux-8, rockylinux-9]
          for-packager: 'true'
          filters:
            tags:
              only: '/^\d+\.\d+\.\d+(\.\d+)?$/'
            branches:
              ignore: '/.*/'
      -
        kazoo/build:
          context: Private-Builds
          name: 'beams-<< matrix.platform >>'
          platform: '<< matrix.platform >>'
          matrix:
            parameters:
              platform: [centos-7, rockylinux-8, rockylinux-9]
          requires:
            - 'preparation-<< matrix.platform >>'
          filters:
            tags:
              only: '/^\d+\.\d+\.\d+(\.\d+)?$/'
            branches:
              ignore: '/.*/'
      -
        kazoo/eunit-tests:
          context: Private-Builds
          requires:
            - preparation-centos-7
          filters:
            tags:
              only: '/^\d+\.\d+\.\d+(\.\d+)?$/'
            branches:
              ignore: '/.*/'
      -
        kazoo/code-checks:
          requires:
            - beams-centos-7
          filters:
            tags:
              only: '/^\d+\.\d+\.\d+(\.\d+)?$/'
            branches:
              ignore: '/.*/'
      -
        kazoo/docs:
          requires:
            - beams-centos-7
          filters:
            tags:
              only: '/^\d+\.\d+\.\d+(\.\d+)?$/'
            branches:
              ignore: '/.*/'
      -
        kazoo/analyze:
          requires:
            - beams-centos-7
          filters:
            tags:
              only: '/^\d+\.\d+\.\d+(\.\d+)?$/'
            branches:
              ignore: '/.*/'
      -
        kazoo/integration-test:
          requires:
            - beams-centos-7
          filters:
            tags:
              only: '/^\d+\.\d+\.\d+(\.\d+)?$/'
            branches:
              ignore: '/.*/'
      -
        kazoo/build-centos7:
          context: Private-Builds
          target-type: kapp
          requires:
            - beams-centos-7
          filters:
            tags:
              only: '/^\d+\.\d+\.\d+(\.\d+)?$/'
            branches:
              ignore: '/.*/'
      -
        kazoo/build-rockylinux8:
          context: Private-Builds
          target-type: kapp
          requires:
            - beams-rockylinux-8
          filters:
            tags:
              only: '/^\d+\.\d+\.\d+(\.\d+)?$/'
            branches:
              ignore: '/.*/'
      -
        kazoo/build-rockylinux9:
          context: Private-Builds
          target-type: kapp
          requires:
            - beams-rockylinux-9
          filters:
            tags:
              only: '/^\d+\.\d+\.\d+(\.\d+)?$/'
            branches:
              ignore: '/.*/'
